INFO:root:using device: cpu
INFO:root:processing subjects: [1, 5, 6, 7, 8]
INFO:root:Training data loader called. len - 5
INFO:root:processing subjects: [9, 11]
INFO:root:Validation data loader called. len - 5
INFO:root:Start training procedure
Traceback (most recent call last):
  File "/home/datta/lab/HPE3D/src/train.py", line 182, in <module>
    main()
  File "/home/datta/lab/HPE3D/src/train.py", line 106, in main
    optimizer, epoch, vae_type)
  File "/home/datta/lab/HPE3D/src/trainer.py", line 24, in training_epoch
    output = _training_step(batch, batch_idx, model)
  File "/home/datta/lab/HPE3D/src/trainer.py", line 88, in _training_step
    loss_val = recon_loss + config.beta * kld_loss
NameError: name 'config' is not defined
