2020-05-13 07:37:36,148 DEBUG   MainThread:5413 [wandb_config.py:_load_defaults():122] no defaults not found in config-defaults.yaml
2020-05-13 07:37:36,153 DEBUG   MainThread:5413 [meta.py:setup():100] code probe starting
2020-05-13 07:37:36,154 DEBUG   MainThread:5413 [meta.py:_setup_code_git():49] probe for git information
2020-05-13 07:37:36,168 DEBUG   MainThread:5413 [meta.py:_setup_code_program():58] save program starting
2020-05-13 07:37:36,169 DEBUG   MainThread:5413 [meta.py:_setup_code_program():60] save program starting: /home/datta/lab/HPE3D/src/train.py
2020-05-13 07:37:36,169 DEBUG   MainThread:5413 [meta.py:_setup_code_program():68] save program saved: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/code/src/train.py
2020-05-13 07:37:36,169 DEBUG   MainThread:5413 [meta.py:_setup_code_program():70] save program
2020-05-13 07:37:36,169 DEBUG   MainThread:5413 [meta.py:setup():122] code probe done
2020-05-13 07:37:36,173 DEBUG   MainThread:5413 [run_manager.py:__init__():546] Initialized sync for hpe/15z0db5i
2020-05-13 07:37:36,176 INFO    MainThread:5413 [run_manager.py:wrap_existing_process():1148] wrapping existing process 5386
2020-05-13 07:37:36,176 WARNING MainThread:5413 [io_wrap.py:register():104] SIGWINCH handler was not None: <Handlers.SIG_DFL: 0>
2020-05-13 07:37:36,221 INFO    MainThread:5413 [run_manager.py:init_run():927] system metrics and metadata threads started
2020-05-13 07:37:36,221 INFO    MainThread:5413 [run_manager.py:init_run():966] upserting run before process can begin, waiting at most 10 seconds
2020-05-13 07:37:36,479 INFO    Thread-14 :5413 [run_manager.py:_upsert_run():1051] saving patches
2020-05-13 07:37:36,535 INFO    Thread-14 :5413 [run_manager.py:_upsert_run():1055] saving pip packages
2020-05-13 07:37:36,536 INFO    Thread-14 :5413 [run_manager.py:_upsert_run():1057] initializing streaming files api
2020-05-13 07:37:36,537 INFO    Thread-14 :5413 [run_manager.py:_upsert_run():1064] unblocking file change observer, beginning sync with W&B servers
2020-05-13 07:37:36,538 INFO    MainThread:5413 [run_manager.py:wrap_existing_process():1165] informing user process we are ready to proceed
2020-05-13 07:37:36,544 INFO    MainThread:5413 [run_manager.py:_sync_etc():1272] entering loop for messages from user process
2020-05-13 07:37:36,547 INFO    MainThread:5413 [run_manager.py:_sync_etc():1295] received message from user process: {"save_policy": {"glob": "events.out.tfevents.1589348256.Datta.5386.0", "policy": "live"}}
2020-05-13 07:37:37,155 INFO    Thread-3  :5413 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/config.yaml
2020-05-13 07:37:37,397 INFO    Thread-3  :5413 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/wandb-metadata.json
2020-05-13 07:37:37,398 INFO    Thread-3  :5413 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/code/src/train.py
2020-05-13 07:37:37,399 INFO    Thread-3  :5413 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/requirements.txt
2020-05-13 07:37:37,399 INFO    Thread-3  :5413 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/output.log
2020-05-13 07:37:37,400 INFO    Thread-3  :5413 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/diff.patch
2020-05-13 07:37:37,402 INFO    Thread-3  :5413 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/events.out.tfevents.1589348256.Datta.5386.0
2020-05-13 07:37:37,404 INFO    Thread-3  :5413 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/code/src
2020-05-13 07:37:37,404 INFO    Thread-3  :5413 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/code
2020-05-13 07:37:38,154 INFO    Thread-3  :5413 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/output.log
2020-05-13 07:37:39,158 INFO    Thread-3  :5413 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/output.log
2020-05-13 07:37:40,158 INFO    Thread-3  :5413 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/output.log
2020-05-13 07:37:41,159 INFO    Thread-3  :5413 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/output.log
2020-05-13 07:37:42,162 INFO    Thread-3  :5413 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/output.log
2020-05-13 07:37:43,160 INFO    Thread-3  :5413 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/output.log
2020-05-13 07:37:44,161 INFO    Thread-3  :5413 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/output.log
2020-05-13 07:37:45,161 INFO    Thread-3  :5413 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/output.log
2020-05-13 07:37:46,162 INFO    Thread-3  :5413 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/output.log
2020-05-13 07:37:47,163 INFO    Thread-3  :5413 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/output.log
2020-05-13 07:37:48,164 INFO    Thread-3  :5413 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/output.log
2020-05-13 07:37:49,164 INFO    Thread-3  :5413 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/output.log
2020-05-13 07:37:50,165 INFO    Thread-3  :5413 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/output.log
2020-05-13 07:37:50,166 INFO    Thread-3  :5413 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/events.out.tfevents.1589348256.Datta.5386.0
2020-05-13 07:37:51,169 INFO    Thread-3  :5413 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/output.log
2020-05-13 07:37:52,168 INFO    Thread-3  :5413 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/output.log
2020-05-13 07:37:53,168 INFO    Thread-3  :5413 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/output.log
2020-05-13 07:37:53,169 INFO    Thread-3  :5413 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/wandb-metadata.json
2020-05-13 07:37:54,172 INFO    Thread-3  :5413 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/output.log
2020-05-13 07:37:54,999 INFO    MainThread:5413 [run_manager.py:_sync_etc():1328] process received interrupt signal, shutting down
2020-05-13 07:37:55,000 INFO    MainThread:5413 [run_manager.py:_sync_etc():1381] closing log streams and sending exitcode to W&B
2020-05-13 07:37:55,002 INFO    MainThread:5413 [run_manager.py:shutdown():1071] shutting down system stats and metadata service
2020-05-13 07:37:55,173 INFO    Thread-3  :5413 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/output.log
2020-05-13 07:37:55,173 INFO    Thread-3  :5413 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/wandb-history.jsonl
2020-05-13 07:37:55,174 INFO    Thread-3  :5413 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/wandb-events.jsonl
2020-05-13 07:37:55,297 INFO    MainThread:5413 [run_manager.py:shutdown():1085] stopping streaming files and file change observer
2020-05-13 07:37:56,174 INFO    Thread-3  :5413 [run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/wandb-metadata.json
2020-05-13 07:37:56,176 INFO    MainThread:5413 [run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/wandb-summary.json
2020-05-13 07:37:58,798 INFO    MainThread:5413 [run_manager.py:_sync_etc():1393] process only ran for 23 seconds, not syncing files
reaming files and file change observer
2020-05-13 07:37:56,174 INFO    Thread-3  :5413 [15z0db5i:run_manager.py:_on_file_modified():691] file/dir modified: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/wandb-metadata.json
2020-05-13 07:37:56,176 INFO    MainThread:5413 [15z0db5i:run_manager.py:_on_file_created():680] file/dir created: /home/datta/lab/HPE3D/wandb/run-20200513_053735-15z0db5i/wandb-summary.json
2020-05-13 07:37:58,798 INFO    MainThread:5413 [15z0db5i:run_manager.py:_sync_etc():1393] process only ran for 23 seconds, not syncing files
